image:
  repository: tccr.io/truecharts/couchpotato
  pullPolicy: IfNotPresent
  tag: v2021.11.22

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 5050
        port: 5050

persistence:
  varrun:
    enabled: true
