apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: CHARTNAME
version: 0.0.1
appVersion: 1.0.0
description: CHARTNAME App for TrueNAS SCALE
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/charts/stable/CHARTNAME
icon: https://raw.githubusercontent.com/truecharts/apps/master/stable/CHARTNAME/icon.png?raw=true
keywords:
  - CHARTNAME
sources:
  - https://github.com/truecharts/apps/tree/master/charts/CHARTNAME
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.18
    # condition:
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
    - test
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
