image:
  repository: tccr.io/truecharts/hedgedoc
  pullPolicy: IfNotPresent
  tag: v1.9.2

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568
  CMD_DOMAIN: ""
  CMD_PROTOCOL_USESSL: false
  CMD_URL_ADDPORT: true
  # TODO: mariadb
service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 3000

persistence:
  varrun:
    enabled: true
