image:
  repository: tccr.io/truecharts/hedgedoc
  pullPolicy: IfNotPresent
  tag: v1.9.2

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568
  CMD_DOMAIN: ""
  CMD_PROTOCOL_USESSL: false
  CMD_URL_ADDPORT: true
  DB_NAME: "hedgedoc"
  DB_USER: "hedgedoc"

envValueFrom:
  DB_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainhost
  DB_PASS:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 3000

persistence:
  varrun:
    enabled: true

mariadb:
  enabled: true
  mariadbUsername: hedgedoc
  mariadbDatabase: hedgedoc
  existingSecret: "mariadbcreds"
