image:
  repository: tccr.io/truecharts/htpcmanager
  pullPolicy: IfNotPresent
  tag: v2021.11.17

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8085
        port: 8085

persistence:
  varrun:
    enabled: true
