image:
  repository: tccr.io/truecharts/boinc
  pullPolicy: IfNotPresent
  tag: v18.04.1

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secret:
  # PASSWORD: ""  (Optional)

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
