image:
  repository: tccr.io/truecharts/dokuwiki
  pullPolicy: IfNotPresent
  tag: v2021.11.28

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 80
        port: 80

persistence:
  varrun:
    enabled: true
