apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: libreoffice
version: 0.0.1
appVersion: 1.0.0
description: libreoffice App for TrueNAS SCALE
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/charts/stable/libreoffice
icon: https://raw.githubusercontent.com/truecharts/apps/master/stable/libreoffice/icon.png?raw=true
keywords:
  - libreoffice
sources:
  - https://hub.docker.com/r/linuxserver/libreoffice
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.16
  # condition:
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - incubator
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
