apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: nano-wallet
version: 0.0.1
appVersion: 1.0.0
description: nano-wallet App for TrueNAS SCALE
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/charts/stable/nano-wallet
icon: https://raw.githubusercontent.com/truecharts/apps/master/stable/nano-wallet/icon.png?raw=true
keywords:
  - nano-wallet
sources:
  - https://hub.docker.com/r/linuxserver/nano-wallet
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.16
  # condition:
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - incubator
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
