image:
  repository: tccr.io/truecharts/nano-wallet
  pullPolicy: IfNotPresent
  tag: v1.3.2

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 80
        port: 80

persistence:
  varrun:
    enabled: true
