image:
  repository: tccr.io/truecharts/minisatip
  pullPolicy: IfNotPresent
  tag: v2021.12.01

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8875
        port: 8875

persistence:
  varrun:
    enabled: true
