image:
  repository: tccr.io/truecharts/scrutiny
  pullPolicy: IfNotPresent
  tag: v2021.11.18

securityContext:
  runAsNonRoot: false
  privileged: true
  allowPrivilegeEscalation: true

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 8080

persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: /config
  udev:
    type: hostPath
    hostPath: /run/udev
    mountPath: /run/udev
    readOnly: true
