image:
  repository: tccr.io/truecharts/firefox
  pullPolicy: IfNotPresent
  tag: v78.15.0

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 3000

persistence:
  varrun:
    enabled: true
