image:
  repository: tccr.io/truecharts/chevereto
  pullPolicy: IfNotPresent
  tag: v1.5.1

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568
  CHEVERETO_DB_DRIVER: mysql
  CHEVERETO_DB_NAME: "chevereto"
  CHEVERETO_DB_USER: "chevereto"

envValueFrom:
  CHEVERETO_DB_HOST:
    secretKeyRef:
      name: mariadbcreds
      key: plainporthost
  CHEVERETO_DB_PASS:
    secretKeyRef:
      name: mariadbcreds
      key: mariadb-password

service:
  main:
    ports:
      main:
        targetPort: 80
        port: 80

persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: true

mariadb:
  enabled: true
  mariadbUsername: chevereto
  mariadbDatabase: chevereto
  existingSecret: "mariadbcreds"
