image:
  repository: tccr.io/truecharts/pydio-cells
  pullPolicy: IfNotPresent
  tag: v3.0.3

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 8080

persistence:
  varrun:
    enabled: true
