image:
  repository: tccr.io/truecharts/znc
  pullPolicy: IfNotPresent
  tag: v1.8.2

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 6501
        port: 6501

persistence:
  varrun:
    enabled: true
