image:
  repository: tccr.io/truecharts/navidrome
  pullPolicy: IfNotPresent
  tag: v0.47.0@sha256:18e691ba523ac0100e28e8d76ef34c2b15e78bb951c0aaf5d846366f756e0ab6

service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533

env:
  ND_SCANINTERVAL: "15m"
  ND_LOGLEVEL: "info"
  ND_SESSIONTIMEOUT: "24h"
  ND_ENABLETRANSCODINGCONFIG: "true"
  ND_MUSICFOLDER: "/music"
  ND_BASEURL: "/navidrome"


persistence:
  data:
    enabled: true
    mountPath: "/data"
