image:
  repository: tccr.io/truecharts/habridge
  pullPolicy: IfNotPresent
  tag: v5.4.0

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 8080

persistence:
  varrun:
    enabled: true
