apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: ipfs
version: 0.0.1
appVersion: 1.0.0
description: ipfs App for TrueNAS SCALE
type: application
deprecated: false
home: https://github.com/truecharts/apps/tree/master/charts/stable/ipfs
icon: https://raw.githubusercontent.com/truecharts/apps/master/stable/ipfs/icon.png?raw=true
keywords:
  - ipfs
sources:
  - https://hub.docker.com/r/linuxserver/ipfs
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.16
  # condition:
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - incubator
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
