image:
  repository: tccr.io/truecharts/minetest
  pullPolicy: IfNotPresent
  tag: v5.4.1

securityContext:
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568
  CLI_ARGS: ""

service:
  main:
    ports:
      main:
        protocol: UDP
        targetPort: 30000
        port: 30000

persistence:
  config:
    enabled: true
    mountPath: "/config/.minetest"
  varrun:
    enabled: true
