image:
  repository: tccr.io/truecharts/minetest
  pullPolicy: IfNotPresent
  tag: v5.4.1

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 30000
        port: 30000

persistence:
  varrun:
    enabled: true
