image:
  repository: tccr.io/truecharts/quassel-web
  pullPolicy: IfNotPresent
  tag: v2021.11.18

securityContext:
  runAsNonRoot: false

PodSecurityPolicy:
  runAsUser: 0
  runAsGroup: 0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 64080
        port: 64080

persistence:
  varrun:
    enabled: true
